name: akilli_kapi_guvenlik_sistemi
description: "Yüz tanıma tabanlı akıllı kapı güvenlik sistemi."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Kamera ve Görüntü İşleme
  camera: ^0.10.5+9
  image: ^4.1.7
  image_picker: ^1.0.7

  # Makine Öğrenmesi ve Yüz Tanıma
  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.11.0
  google_mlkit_face_mesh_detection: ^0.1.0
  
  # Veritabanı ve Depolama
  sqflite: ^2.3.2
  sqflite_sqlcipher: ^3.2.0
  path_provider: ^2.1.2
  path: ^1.9.0

  # Donanım ve Sistem Erişimi
  local_auth: ^2.2.0
  system_info2: ^3.0.0

  # Ağ İşlemleri
  http: ^1.2.1

  # Yardımcı Paketler
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Model dosyalarının bulunduğu klasör
  assets:
    - assets/models/
