name: akilli_kapi_guvenlik_sistemi
description: "Yüz tanıma tabanlı akıllı kapı güvenlik sistemi."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Yerelleştirme için eklendi
    sdk: flutter

  # Projenin ana bağımlılıkları
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.11.0
  tflite_flutter: ^0.10.4
  image: ^4.1.7
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  local_auth: ^2.2.0
  google_mlkit_face_mesh_detection: ^0.1.0 # Kullanımda olmasa da bağımlılık olarak kalabilir
  sqflite_sqlcipher: ^2.3.0 # Güvenli depolama için

  # Eylem planı ile eklenen yeni paketler
  http: ^1.2.1
  system_info2: ^3.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/
